services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: nayaashb
      POSTGRES_PASSWORD: Ashu@9348
      POSTGRES_DB: godzilla-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: