# Generated by Django 6.0.3 on 2026-03-12 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "HEALTHY"),
                            ("NOT_WORKING", "NOT_WORKING"),
                            ("LOST", "LOST"),
                            ("SCRAP", "SCRAP"),
                        ],
                        default="HEALTHY",
                        max_length=255,
                    ),
                ),
                ("transfer_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("LOANED", "LOANED"),
                            ("MAINTENANCE", "MAINTENANCE"),
                        ],
                        default="AVAILABLE",
                        max_length=255,
                    ),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currently_held_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_detail",
            },
        ),
        migrations.CreateModel(
            name="DeviceTransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("LOAN", "LOAN"), ("TRANSFER", "TRANSFER")],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.devicedetailsmodel",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_transaction",
            },
        ),
        migrations.AddIndex(
            model_name="devicedetailsmodel",
            index=models.Index(
                fields=["primary_owner", "created_at"], name="user_created_index"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetransactionmodel",
            index=models.Index(
                fields=["status", "created_at"], name="status_created_index"
            ),
        ),
    ]
